---
    RANDOM_SEED: 42
    TRAIN_PERIOD: 84
    TEST_PERIOD: 28
    NUM_LAYERS: 8
    BATCH_SIZE: 16384
    DROPOUT: 0.05
    N_EPOCHS: 1000
    INITIAL_LEARNING_RATE: 0.002
    FINAL_LEARNING_RATE: 0.001
    USE_VALIDATION: true
    SAVE_VAL_ERRORS: true
    DATA_PATH: sales_train_validation.csv